// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyPSiYTVnfXUEKOo9UIo7K9RRJTenS5KY',
    appId: '1:991323594383:web:6854f14d545507c1b65afa',
    messagingSenderId: '991323594383',
    projectId: 'hogwarts-authentication',
    authDomain: 'hogwarts-authentication.firebaseapp.com',
    storageBucket: 'hogwarts-authentication.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYJ4Lg4wgOqYjvmXGqWL5ix2jDxJfIqRU',
    appId: '1:991323594383:android:913a2488f22d1f61b65afa',
    messagingSenderId: '991323594383',
    projectId: 'hogwarts-authentication',
    storageBucket: 'hogwarts-authentication.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZRYHHGbHXdbjXmDmuF9QelZsePoDZ1ws',
    appId: '1:991323594383:ios:be09ab0231e1bf04b65afa',
    messagingSenderId: '991323594383',
    projectId: 'hogwarts-authentication',
    storageBucket: 'hogwarts-authentication.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask2',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZRYHHGbHXdbjXmDmuF9QelZsePoDZ1ws',
    appId: '1:991323594383:ios:be09ab0231e1bf04b65afa',
    messagingSenderId: '991323594383',
    projectId: 'hogwarts-authentication',
    storageBucket: 'hogwarts-authentication.firebasestorage.app',
    iosBundleId: 'com.example.flutterTask2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDyPSiYTVnfXUEKOo9UIo7K9RRJTenS5KY',
    appId: '1:991323594383:web:cbed7300f8b7a4e9b65afa',
    messagingSenderId: '991323594383',
    projectId: 'hogwarts-authentication',
    authDomain: 'hogwarts-authentication.firebaseapp.com',
    storageBucket: 'hogwarts-authentication.firebasestorage.app',
  );
}
